### ISSUE TITLE
Failed to compress video in android 

### ISSUE THREAD

**Issue by engr-erum** [Tourenathan-G5organisation/SiliCompressor#11]
I write this code but getting error : 

 class VideoCompressAsyncTask extends AsyncTask<String, String, String> {

        Context mContext;

        public VideoCompressAsyncTask(Context context){
            mContext = context;
        }

        @Override
        protected void onPreExecute() {
            super.onPreExecute();
        }

        @Override
        protected String doInBackground(String... paths) {
            String filePath = null;
            try {
                sourceUriString = "/storage/emulated/0/DCIM/Camera/A.mp4";
                String destinationUriString = "/storage/emulated/0/videokit";
                filePath = SiliCompressor.with(mContext).compressVideo(sourceUriString, destinationUriString);
                Log.d(MainActivity.class.getName() , "filePath : "+filePath);
            } catch (URISyntaxException e) {
                e.printStackTrace();
            }
            return  filePath;

        }

        @Override
        protected void onPostExecute(String compressedFilePath) {
            super.onPostExecute(compressedFilePath);
            File imageFile = new File(compressedFilePath);
            float length = imageFile.length() / 1024f; // Size in KB
            String value;
            if(length >= 1024)
                value = length/1024f+" MB";
            else
                value = length+" KB";
            Log.i("Silicompressor", "Path: "+value);
        }
    }

calling from onCreate()
{
        String  sourceUriString = "/storage/emulated/0/DCIM/Camera/A.mp4";
        String destinationUriString = "/sdcard/videokit/new_compress.mp4";
        File f = new File(Environment.getExternalStorageDirectory() + "/videokit/C.mp4");
        Log.d(MainActivity.class.getName() , "getName:"+f.getName());
        Log.d(MainActivity.class.getName() , "path:"+f.getPath());

        File f1 = new File(Environment.getExternalStorageDirectory().getAbsolutePath() + "/videokit");
        new VideoCompressAsyncTask(this).execute(f.getPath().toString(), f1.getPath().toString());

}

FATAL EXCEPTION: AsyncTask #1
                                                                             Process: com.silicompressorapplication, PID: 3103
                                                                             java.lang.RuntimeException: An error occured while executing doInBackground()
                                                                                 at android.os.AsyncTask$3.done(AsyncTask.java:300)
                                                                                 at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                                                                                 at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                                                                                 at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                                 at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                 at java.lang.Thread.run(Thread.java:841)
                                                                              Caused by: java.lang.IllegalArgumentException
                                                                                 at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:63)
                                                                                 at com.iceteck.silicompressorr.videocompression.MediaController.convertVideo(MediaController.java:252)
                                                                                 at com.iceteck.silicompressorr.SiliCompressor.compressVideo(SiliCompressor.java:300)
                                                                                 at com.silicompressorapplication.MainActivity$VideoCompressAsyncTask.doInBackground(MainActivity.java:51)
                                                                                 at com.silicompressorapplication.MainActivity$VideoCompressAsyncTask.doInBackground(MainActivity.java:32)
                                                                                 at android.os.AsyncTask$2.call(AsyncTask.java:288)
                                                                                 at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                 at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
                                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                                 at java.lang.Thread.run(Thread.java:841)

**Comment by engr-erum** [comment]
@Tourenathan-G5organisation  can u pls look into it ?

**Comment by Tourenathan-G5organisation** [comment]
@engr-erum Are you sure the source file exist?  have you added the android.permission.WRITE_EXTERNAL_STORAGE to your application? Are you sure your paths are well formulated?

**Comment by engr-erum** [comment]
@Tourenathan-G5organisation i am not sure about paths but have given write external storage permission and had added source file as well

**Comment by engr-erum** [comment]
i can add complete zip file of my project please check is this the issue with path ? 
https://drive.google.com/a/arpatech.com/file/d/0B4yf4j9pXergRHFiVjRVSTk3R00/view?usp=sharing @Tourenathan-G5organisation

**Comment by muvans** [comment]
Same error here:
-android.permission.WRITE_EXTERNAL_STORAGE is added
-File Path and Destination directories in place
 Error remains: setSource is NULL?
IllegalArgumentException at android.media.MediaMetadataRetriever.setDataSource

**Comment by engineers-bojan** [comment]
The library is trying to access to extract the absolute file path from a String URI and since you are sending an actual absolute file path the error occurrs..

@Tourenathan-G5organisation It would be good if you could add the compressVideo method that accepts an absolute file path.

**Comment by Tourenathan-G5organisation** [comment]
Hello @engr-erum @muvans @engineers-bojan ,
The new version of this library has solved this problem.
Now you can passed either the video path or Uri as source of the video.

**Comment by sidAli1993** [comment]
![sdfsdf](https://user-images.githubusercontent.com/18312141/31723313-ee66de06-b437-11e7-9d5b-c0eb40ac6e17.png)

I am trying to compress video , but got this output, Please get me out of this trouble.
new VideoCompressAsyncTask(this).execute(data.getData().toString(), f.getPath());

**Comment by rahulpatidar009** [comment]
I also try to compress video from file path using below code snippet-
`new VideoCompressAsyncTask(SelectPictureActivity.this).execute(sourceFilePath, destinationFilePath);`

But unfortunately getting this exception.
Here destinationFilePath is directory in which I want to save compressed file. I have also tried to pass the exact file path but still getting same error.

Caused by: java.lang.RuntimeException: setDataSource failed: status = 0x80000000
                                                                      at android.media.MediaMetadataRetriever.setDataSource(Native Method)
                                                                      at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:71)
                                                                      at com.iceteck.silicompressorr.videocompression.MediaController.convertVideo(MediaController.java:272)
                                                                      at com.iceteck.silicompressorr.SiliCompressor.compressVideo(SiliCompressor.java:353)
                                                                      at com.iceteck.silicompressorr.SiliCompressor.compressVideo(SiliCompressor.java:301)
                                                                      at com.gopromanager.activity.GoproActivity$VideoCompressAsyncTask.doInBackground(GoproActivity.java:242)
                                                                      at com.gopromanager.activity.GoproActivity$VideoCompressAsyncTask.doInBackground(GoproActivity.java:226)
                                                                      at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234) 
                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                      at java.lang.Thread.run(Thread.java:818)

**Comment by Tourenathan-G5organisation** [comment]
Hello
Please try on a real device with the latest version 2.2.3

**Comment by Pankaj-Sati** [comment]
@Tourenathan-G5organisation Still getting the above eror in latest version(2.2.3)

```
Caused by: java.lang.IllegalArgumentException
        at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:71)
```
