### ISSUE TITLE
IllegalArgumentException at android.media.MediaMetadataRetriever.setDataSource

### ISSUE THREAD

**Issue by RushiMThakker** [Tourenathan-G5organisation/SiliCompressor#14]
I am passing correct Source and Destination URI String in Compressing video function, still I am getting IllegalArgumentException. Please Help.

filePath = SiliCompressor.with((ActCreateVideo.this)).compressVideo(recordedVideoURI.getPath(), compressedVideoURI.getPath());

Here URIs are defined as:

recordedVideoURI = FileProvider.getUriForFile(context, BuildConfig.APPLICATION_ID + ".provider",recordedFileWithinMyDir);
compressedVideoURI = Uri.parse("content://xyz/external_files/" + folder_main +File.separator+ "VID_COMPRESSED_" + timeStamp + ".mp4");

Error Log:

                      Caused by: java.lang.IllegalArgumentException
                                                             at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:64)
                                                             at com.iceteck.silicompressorr.videocompression.MediaController.convertVideo(MediaController.java:252)
                                                             at com.iceteck.silicompressorr.SiliCompressor.compressVideo(SiliCompressor.java:300)
                                                             at com.igb.ActCreateVideo.onActivityResult(ActCreateVideo.java:128)
                                                             at android.app.Activity.dispatchActivityResult(Activity.java:6931)
                                                             at android.app.ActivityThread.deliverResults(ActivityThread.java:4090)
                                                             at android.app.ActivityThread.handleSendResult(ActivityThread.java:4137) 
                                                             at android.app.ActivityThread.-wrap20(ActivityThread.java) 
                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1529) 
                                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                             at android.os.Looper.loop(Looper.java:154) 
                                                             at android.app.ActivityThread.main(ActivityThread.java:6123) 
                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867) 
                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)

**Comment by narendra88** [comment]
Even I am getting same error

**Comment by narendra88** [comment]
@RushiMThakker your issue seems to be of content Uri. You need to pass file uri, which you can get using FilePath, just like 
`Uri  capturedUri = Uri.fromFile(fileObject);`

**Comment by AganCN** [comment]
Use MediaController.getInstance().convertVideo(paths[0], new File(paths[1]));

**Comment by narendra88** [comment]
@AganCN  what may be the cause of **dequeueOutputBuffer()** in a few of the devices? My issue is mentioned [here](https://github.com/Tourenathan-G5organisation/SiliCompressor/issues/16) as well.

**Comment by RushiMThakker** [comment]
@narendra88 I stopped using this library because contributors doesn't seem to be active in solving issues. Instead I used FFMpeg Android Wrapper to compress video and it works great. Regarding your suggesstion, Uri.fromFile is no longer supported and is not a safe method to handle Uris. You can check [this ](https://commonsware.com/blog/2014/07/04/uri-not-necessarily-file.html)blog of CommonsWare.

**Comment by narendra88** [comment]
@RushiMThakker Hi, can you please suggest any good reference / sample for the same - FFMpeg Android Wrapper?

**Comment by RushiMThakker** [comment]
@narendra88 I used [this](https://github.com/WritingMinds/ffmpeg-android-java). No doubt this one is also slow and all of them are going to be slow because video compression and then rendering are highly cpu intensive tasks and mobile devices don't support that high end processors or GPU. But surely, you can make some tweaks regarding scaling and encoding formats that would decrease file size to a large extent. I don't know how youtube application works so smoothly. They have done fantastic work. Also you can compress in background service so that it won't block GUI,

**Comment by AmanSharma1988** [comment]
@RushiMThakker I also got same error but able to resolve. As from your code i seen URI created is not correct. Try passing URI which we get from Uri selectedUri = data.getData(); in OnActivityResult while picking file from gallery.
It should be formatted like this : 
content://com.android.providers.media.documents/document/video%3A33049
