### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/googlecode/mp4parser/util/Matrix

### ISSUE THREAD

**Issue by abhidiwakar** [Tourenathan-G5organisation/SiliCompressor#146]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.anstrontechnologies.videocompressor, PID: 21291
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/googlecode/mp4parser/util/Matrix;
        at com.iceteck.silicompressorr.videocompression.Mp4Movie.<init>(Mp4Movie.java:22)
        at com.iceteck.silicompressorr.videocompression.MediaController.convertVideo(MediaController.java:386)
        at com.iceteck.silicompressorr.videocompression.MediaController.convertVideo(MediaController.java:294)
        at com.iceteck.silicompressorr.SiliCompressor.compressVideo(SiliCompressor.java:216)
        at com.iceteck.silicompressorr.SiliCompressor.compressVideo(SiliCompressor.java:178)
        at com.anstrontechnologies.videocompressor.MainActivity.compressVideoFile(MainActivity.kt:73)
        at com.anstrontechnologies.videocompressor.MainActivity.access$compressVideoFile(MainActivity.kt:20)
        at com.anstrontechnologies.videocompressor.MainActivity$onCreate$2.onClick(MainActivity.kt:54)
        at android.view.View.performClick(View.java:5619)
        at android.view.View$PerformClick.run(View.java:22298)
        at android.os.Handler.handleCallback(Handler.java:754)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:165)
        at android.app.ActivityThread.main(ActivityThread.java:6375)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.googlecode.mp4parser.util.Matrix" on path: DexPathList[[zip file "/data/app/com.anstrontechnologies.videocompressor-1/base.apk"],nativeLibraryDirectories=[/data/app/com.anstrontechnologies.videocompressor-1/lib/arm64, /system/lib64, /vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:74)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.iceteck.silicompressorr.videocompression.Mp4Movie.<init>(Mp4Movie.java:22) 
        at com.iceteck.silicompressorr.videocompression.MediaController.convertVideo(MediaController.java:386) 
        at com.iceteck.silicompressorr.videocompression.MediaController.convertVideo(MediaController.java:294) 
        at com.iceteck.silicompressorr.SiliCompressor.compressVideo(SiliCompressor.java:216) 
        at com.iceteck.silicompressorr.SiliCompressor.compressVideo(SiliCompressor.java:178) 
        at com.anstrontechnologies.videocompressor.MainActivity.compressVideoFile(MainActivity.kt:73) 
        at com.anstrontechnologies.videocompressor.MainActivity.access$compressVideoFile(MainActivity.kt:20) 
        at com.anstrontechnologies.videocompressor.MainActivity$onCreate$2.onClick(MainActivity.kt:54) 
        at android.view.View.performClick(View.java:5619) 
        at android.view.View$PerformClick.run(View.java:22298) 
        at android.os.Handler.handleCallback(Handler.java:754) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:165) 
        at android.app.ActivityThread.main(ActivityThread.java:6375) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)

**Comment by algavania** [comment]
You need to add `implementation 'com.googlecode.mp4parser:isoparser:1.1.22'`

**Comment by r17171709** [comment]
1.0.6 is OK

**Comment by M78Code** [comment]
me too, 2.2.2 is Ok!

**Comment by khaledhamdansd** [comment]
same issue with 2.2.2

**Comment by charlieaboumoussa** [comment]
I added implementation 'com.googlecode.mp4parser:isoparser:1.1.22'.
It gives this error: Surface frame wait timed out.
Please if someone can help. Thank you!

**Comment by appach22** [comment]
Upgrading from 2.2.3 to 2.2.4 has helped in my case.

**Comment by DaChelimo** [comment]
> implementation 'com.googlecode.mp4parser:isoparser:1.1.22'

This needs to be stated in the documentation

**Comment by DaChelimo** [comment]
> I added implementation 'com.googlecode.mp4parser:isoparser:1.1.22'.
> It gives this error: Surface frame wait timed out.
> Please if someone can help. Thank you!

This is because the compression is being executed on the Main Thread. Use Async Task or Kotlin Coroutines to handle this.

**Comment by zjianflys** [comment]
Surface frame wait timed out  是因为在主线程运行导致的
