### ISSUE TITLE
Getting NumberFormatException in some cases

### ISSUE THREAD

**Issue by ashu5398** [Tourenathan-G5organisation/SiliCompressor#178]
```
java.lang.NumberFormatException: s == null
        at java.lang.Integer.parseInt(Integer.java:577)
        at java.lang.Integer.valueOf(Integer.java:801)
        at com.iceteck.silicompressorr.videocompression.MediaController.convertVideo(MediaController.java:283)
        at com.iceteck.silicompressorr.SiliCompressor.compressVideo(SiliCompressor.java:185)
        at com.iceteck.silicompressorr.SiliCompressor.compressVideo(SiliCompressor.java:168)
```

**Comment by a365344743s** [comment]
try this [MediaCompressTelegram](https://github.com/a365344743s/MediaCompressTelegram)
or [MediaCompressSignal](https://github.com/a365344743s/MediaCompressSignal)
