### ISSUE TITLE
Crashing on Android 12

### ISSUE THREAD

**Issue by manumathew17** [Tourenathan-G5organisation/SiliCompressor#179]
getting crash on android 12

`    java.lang.RuntimeException: setDataSource failed: status = 0xFFFFFFEA
        at android.media.MediaMetadataRetriever._setDataSource(Native Method)
        at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:284)
        at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:248)
        at com.iceteck.silicompressorr.videocompression.MediaController.convertVideo(MediaController.java:304)
        at com.iceteck.silicompressorr.videocompression.MediaController.convertVideo(MediaController.java:271)
        at com.iceteck.silicompressorr.SiliCompressor.compressVideo(SiliCompressor.java:192)
        at com.iceteck.silicompressorr.SiliCompressor.compressVideo(SiliCompressor.java:164)`

**Comment by a365344743s** [comment]
try this [MediaCompressTelegram](https://github.com/a365344743s/MediaCompressTelegram)
or [MediaCompressSignal](https://github.com/a365344743s/MediaCompressSignal)
