### ISSUE TITLE
please solve my error

### ISSUE THREAD

**Issue by pawankevin** [Tourenathan-G5organisation/SiliCompressor#3]
10-06 00:33:57.306 21238-21384/? E/CursorWindow: Failed to read row 0, column -1 from a CursorWindow which has 1 rows, 6 columns.
10-06 00:33:57.309 21238-21384/? E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
                                                   Process: com.example.pawan.compressor, PID: 21238
                                                   Theme: themes:{default=overlay:com.cyngn.hexo, iconPack:com.cyngn.hexo, fontPkg:com.cyngn.hexo, com.android.systemui=overlay:com.cyngn.hexo, com.android.systemui.navbar=overlay:com.cyngn.hexo}
                                                   java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                       at android.os.AsyncTask$3.done(AsyncTask.java:309)
                                                       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                       at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                       at java.lang.Thread.run(Thread.java:818)
                                                    Caused by: java.lang.IllegalStateException: Couldn't read row 0, col -1 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
                                                       at android.database.CursorWindow.nativeGetString(Native Method)
                                                       at android.database.CursorWindow.getString(CursorWindow.java:438)
                                                       at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:51)
                                                       at android.database.CursorWrapper.getString(CursorWrapper.java:137)
                                                       at com.iceteck.silicompressorr.SiliCompressor.getRealPathFromURI(SiliCompressor.java:322)
                                                       at com.iceteck.silicompressorr.SiliCompressor.compressImage(SiliCompressor.java:163)
                                                       at com.iceteck.silicompressorr.SiliCompressor.compress(SiliCompressor.java:59)
                                                       at com.example.pawan.compressor.MainActivity$ImageCompressionAsyncTask.doInBackground(MainActivity.java:101)
                                                       at com.example.pawan.compressor.MainActivity$ImageCompressionAsyncTask.doInBackground(MainActivity.java:90)
                                                       at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234) 
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                       at java.lang.Thread.run(Thread.java:818)

**Comment by larrytech7** [comment]
It is safe to call the compress on your main thread, we handle the heavy lifting for you

**Comment by Tourenathan-G5organisation** [comment]
The library is very easy to use. Please check the codes in the demo to see how we have use it. Its always good to run the compression codes from a background task like AsyncTask to avoid blocking the main thread. Hope this help you @pawankevin
