### ISSUE TITLE
crash FileUriExposedException android 7

### ISSUE THREAD

**Issue by 3akat** [Tourenathan-G5organisation/SiliCompressor#32]
Hi,
I'm getting a crash when trying to record video or catching photo.
Nexus 5X, Android 7.1.2
Here is the log
```
FATAL EXCEPTION: main
Process: com.iceteck.silicompressor, PID: 18436
android.os.FileUriExposedException: file:///storage/emulated/0/Movies/VID_20170913_133645_104748790.mp4 exposed beyond app through ClipData.Item.getUri()
at android.os.StrictMode.onFileUriExposed(StrictMode.java:1796)
at android.net.Uri.checkFileUriExposed(Uri.java:2346)
at android.content.ClipData.prepareToLeaveProcess(ClipData.java:845)
at android.content.Intent.prepareToLeaveProcess(Intent.java:8941)
at android.content.Intent.prepareToLeaveProcess(Intent.java:8926)
at android.app.Instrumentation.execStartActivity(Instrumentation.java:1517)
at android.app.Activity.startActivityForResult(Activity.java:4228)
at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:50)
at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:79)
at android.app.Activity.startActivityForResult(Activity.java:4186)
at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:859)
at com.iceteck.silicompressor.SelectPictureActivity.dispatchTakeVideoIntent(SelectPictureActivity.java:208)
at com.iceteck.silicompressor.SelectPictureActivity.requestPermissions(SelectPictureActivity.java:105)
at com.iceteck.silicompressor.SelectPictureActivity.access$000(SelectPictureActivity.java:34)
at com.iceteck.silicompressor.SelectPictureActivity$2.onClick(SelectPictureActivity.java:75)
at android.view.View.performClick(View.java:5637)
at android.view.View$PerformClick.run(View.java:22429)
at android.os.Handler.handleCallback(Handler.java:751)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6121)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

**Comment by Tourenathan-G5organisation** [comment]
@3akat thanks for your feedback.
Yes, this is a problem that comes with Android 7.
This will be solved whn making this library available for Adroid 7. We are working on that

**Comment by gokrish6670** [comment]
@Tourenathan-G5organisation  @larrytech7  when it will be fixed..im already using in mu project android 5 , 6 are working but not on android 7

**Comment by Tourenathan-G5organisation** [comment]
Hello @gokukish 
Here comes a new version of the library in which this problem has been solved.
Hope this help
