### ISSUE TITLE
It crashes the app when you select an image from Recent Images

### ISSUE THREAD

**Issue by CurvesTech** [Tourenathan-G5organisation/SiliCompressor#59]
I use gallery intent and when i select image from gallery, it works perfectly, but if i choose an image from Recent images section, it crashes the app. Following is the output in the logcat.

Couldn't read row 0, col -1 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
                                                                                        at android.database.CursorWindow.nativeGetString(Native Method)
                                                                                        at android.database.CursorWindow.getString(CursorWindow.java:438)

**Comment by larrytech7** [comment]
Hello @CurvesTech can you show us how to reproduce this issue please?

**Comment by Tourenathan-G5organisation** [comment]
Hi @CurvesTech 
We will test with the scenario you mentioned and will let you know
