### ISSUE TITLE
Illegal Argument Exception

### ISSUE THREAD

**Issue by brijhub** [Tourenathan-G5organisation/SiliCompressor#62]
Please have a look.
Here is my error

On this Line
                            File f = new File(Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_PICTURES), "MyApp" + "/Dirtectory");

```
 java.lang.IllegalArgumentException
                                                                          at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:73)
                                                                          at com.iceteck.silicompressorr.videocompression.MediaController.convertVideo(MediaController.java:272)
                                                                          at com.iceteck.silicompressorr.SiliCompressor.compressVideo(SiliCompressor.java:353)
                                                                          at com.iceteck.silicompressorr.SiliCompressor.compressVideo(SiliCompressor.java:301)
                                                                          at com.trenderalert.app.Activity.SetTrend_Activity$14.onResponse(SetTrend_Activity.java:1274)
                                                                          at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:70)
                                                                          at android.os.Handler.handleCallback(Handler.java:742)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at android.os.Looper.loop(Looper.java:157)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5555)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:635)
```

**Comment by brijhub** [comment]
I got the solution since I was passing uri.toString() instead of Uri.
Thanks for your library so I'm closing this issue.
