### ISSUE TITLE
what to pass as arguments 

### ISSUE THREAD

**Issue by mountaineer59** [Tourenathan-G5organisation/SiliCompressor#85]
`fileUri` is simply uri of the image im passing as first argument and `path` is 

```

File mediaStorageDir = new File(Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_PICTURES), IMAGE_DIRECTORY_NAME);
            String path = mediaStorageDir.toString();
            path = path + "/" + getRandomString() + ".mp4";
     new VideoCompressAsyncTask(MyActivity.this).execute(new File(fileUri.toString()).toString(), path);

```

and inside asynctask , when I execute this line, I get the error  
`                filePath = SiliCompressor.with(mContext).compressVideo(paths[0], paths[1]);
`

here's the error
` Caused by: java.lang.IllegalArgumentException
        at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:71)
        at com.iceteck.silicompressorr.videocompression.MediaController.convertVideo(MediaController.java:272)
        at com.iceteck.silicompressorr.SiliCompressor.compressVideo(SiliCompressor.java:333)
        at com.iceteck.silicompressorr.SiliCompressor.compressVideo(SiliCompressor.java:316)`

Can anyone help me with this error?

**Comment by Tourenathan-G5organisation** [comment]
Hi @mountaineer59 , it would suggest you to download the project and check how we  did it in the demo app.
